@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor Administrationssekretær
activate Administrationssekretær
loop
Administrationssekretær -> System : Login
activate System
database Database
activate Database
System --> Database: Verificer bruger
alt successful case
Database --> System: Bruger ok
System -> Administrationssekretær: Login accepted (main menu)
else some kind of failure
Database --> System: Invalid bruger
System -> Administrationssekretær: Log in declined
end
end


activate System_teacher
actor Teacher
activate Teacher
System_teacher <- Teacher: Request course schedule
System_teacher -> Database: Send request to Administrationssekretær
Database -> System: Send request to Administrationssekretær
System -> Administrationssekretær: Aprove or decline request
alt successful case
Administrationssekretær --> System : Request aproved
System --> Database: Request aproved
Database --> System_teacher: Request aproved
System_teacher --> Teacher: Show message "Request aproved"
else some kind of failure
Administrationssekretær --> System: Request declined
System --> Database: Request declined
Database --> System_teacher: Request declined
System_teacher --> Teacher: show message "Request declined, try again"
end








@enduml