@startuml
'https://plantuml.com/sequence-diagram

autonumber


actor Teacher
activate Teacher
Teacher -> System: Login
activate System
System ---> Database: Verificer bruger
activate Database
alt successful case
Database --> System: bruger ok
else some kind of failure
System -> Teacher: Menu
Database --> System: Invalid bruger
System -> Teacher: Log ud
end
opt
Teacher -> System: Request course schedule
System -> Administration_system: Send request to administration
actor Secretary
activate Secretary
Administration_system -> Secretary: Approve or decline
Teacher -> System: Chose availiability
System -> Administration_system: Show when the teacher is available
Administration_system -> Secretary: Show availiability
Teacher -> System: Show course schedule
end
alt successful case
activate Administration_system
Secretary --> Administration_system: Answer
Administration_system --> System: Request approved
System -> Teacher: Show updated course schedule
else some kind of failure
Administration_system --> System: Request declined
System -> Teacher: Request new course schedule
end


@enduml