@startuml
'https://plantuml.com/use-case-diagram

@startuml
left to right direction
skinparam packageStyle rectangle
actor Teacher
actor Student
actor Administrationssekretær
actor TA
rectangle Study.net.dk {

    Teacher --> (Request change of  course)
    Teacher ---> (Access Course Information)
    Teacher ---> (request schedule)
    Student ---> (Access Course Information)
    Student ---> (request schedule)
    Administrationssekretær---> (Book classroom)
    Administrationssekretær ---> (change course)
    Administrationssekretær ---> (request teachers availability )
    TA ---> (request change of classroom)
    TA ---> (Access Course Information)
    TA ---> (request schedule)


}
@enduml