@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor Administrationssekretær
activate Administrationssekretær
loop
Administrationssekretær -> System : Login
activate System
database Database
activate Database
System --> Database: verificerUser()
alt successful case
Database --> System: Bruger ok
System -> Administrationssekretær: Login accepted (main menu)
else some kind of failure
Database --> System: Invalid bruger
System -> Administrationssekretær: Log in declined
end
end



actor Teacher

System_teacher <- Teacher: requestCourseSchedule()
activate Teacher
activate System_teacher
System_teacher -> Database: Send request to Administrationssekretær
Database -> System: Send request to Administrationssekretær
System -> Administrationssekretær: approveOrDeclineCourseSchedule()
alt successful case
Administrationssekretær --> System : Request approved
System --> Database: Request approved
Database --> System_teacher: Request approved
System_teacher --> Teacher: Show message "Request approved"
else some kind of failure
Administrationssekretær --> System: Request declined
System --> Database: Request declined
Database --> System_teacher: Request declined
System_teacher --> Teacher: show message "Request declined, try again"
end



@enduml