@startuml
left to right direction
skinparam packageStyle rectangle
actor Professor
actor Student
actor administrationssekretær
actor TA
rectangle Study.net.dk {

    Professor --> (Request change of  course)
    Professor ---> (Access Course Information)
    Professor ---> (request schedule)
    Student ---> (Access Course Information)
    Student ---> (request schedule)
    administrationssekretær---> (Book classroom)
    administrationssekretær ---> (change course)
    administrationssekretær ---> (request professors availability )
    TA ---> (request change of classroom)
    TA ---> (Access Course Information)
    TA ---> (request schedule)


}
@enduml